version: "3.9"
services:
  web:
    image: andythebreaker/yolov5ver7frontenddocker_web:latest
    ports:
      - 59486:5000
      - 59485:22128
      - 59484:43786
      - 59483:30461
  pubhtml:
    image: andythebreaker/phpupdown:latest
    ports:
      - 34821:80
      - 34822:443
      - 34823:9000
      - 34824:48748
